### ISSUE TITLE
MMOItems Mana&Stamina NullPointerExeption

### ISSUE THREAD

**Issue by KNNI** [mmopluginteam/mmoitems#100]
MMOLib version 1.1.2 (spigot)
MMOItems version 5.4 (spigot)
MMOItemsMana version 1.3 (mythicmobs.net)

![image](https://user-images.githubusercontent.com/18620563/81161561-09278600-8f8c-11ea-844f-7a8e7a3e97df.png)

This warning only appears when a player leaves the server. As soon as the player comes back to the server, it will stop spamming this warning into the console.

```
[11:12:17 WARN]: [MMOItemsMana] Task #104 for MMOItemsMana v1.3 generated an exception
java.lang.NullPointerException: null
        at net.Indyuce.mmoitems.addon.mana.Main$1.run(Main.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-239]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-239]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-239]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-239]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-239]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-239]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Indyuce** [comment]
Please pastebin the entire server logs

**Comment by KNNI** [comment]
Here you are:
https://pastebin.com/0UAQaMF4

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
