### ISSUE TITLE
1.16.1Fatal mistake

### ISSUE THREAD

**Issue by kerorozsl** [mmopluginteam/mmoitems#130]
input /mi browse hen click the operation and report an error
[15:19:04] [Server thread/ERROR]: Could not pass event InventoryClickEvent to MMOItems v5.5.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2190) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: minecraft:generic_attack_speed
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:140) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.attribute.CraftAttributeMap.fromMinecraft(CraftAttributeMap.java:30) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaItem.buildModifiers(CraftMetaItem.java:447) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:369) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:527) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.asBukkitCopy(CraftItemStack.java:62) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.mmogroup.mmolib.version.nms.NMSHandler_1_16_R1$NBTItem_v1_15_R1.toItem(NMSHandler_1_16_R1.java:217) ~[?:?]
	at net.Indyuce.mmoitems.api.item.build.MMOItemBuilder.build(MMOItemBuilder.java:117) ~[?:?]
	at net.Indyuce.mmoitems.manager.ItemManager.getItem(ItemManager.java:56) ~[?:?]
	at net.Indyuce.mmoitems.gui.ItemBrowser.getInventory(ItemBrowser.java:140) ~[?:?]
	at net.Indyuce.mmoitems.gui.PluginInventory.open(PluginInventory.java:39) ~[?:?]
	at net.Indyuce.mmoitems.gui.ItemBrowser.whenClicked(ItemBrowser.java:257) ~[?:?]
	at net.Indyuce.mmoitems.gui.listener.GuiListener.a(GuiListener.java:28) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	... 18 more

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOItems, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
