### ISSUE TITLE
Bossshoppro

### ISSUE THREAD

**Issue by minhthanh920** [mmopluginteam/mmoitems#142]
See console log...
 

> [23:53:04 ERROR]: Error occurred while enabling MMOItems v5.5.1 (Is it up to date?)
java.lang.NullPointerException: null
        at org.black_ixx.bossshop.core.rewards.BSRewardType.registerType(BSRewardType.java:60) ~[?:?]
        at org.black_ixx.bossshop.core.rewards.BSRewardType.register(BSRewardType.java:91) ~[?:?]
        at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:225) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Server info:**
 - Paper 1.16.1
 - Plugin Version : 5.5.1
- Bossshop :  2.0.9

**Comment by Joshinn-mc** [comment]
@minhthanh920 Please add BossShopPro as a depend inside of MMOItems plugin.yml and then restart with the new jar.
