### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pwnzeye** [mmopluginteam/mmoitems#163]
10:06:37

[MMOItems]: Task #295 for MMOItems v5.5.3-SNAPSHOT generated an exception

Console
 
10:06:37

java.lang.NullPointerException: null
at net.Indyuce.mmoitems.MMOItems.lambda$null$2(MMOItems.java:184) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262]
at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_262]
at net.Indyuce.mmoitems.MMOItems.lambda$onEnable$3(MMOItems.java:184) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-106]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-106]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
at net.Indyuce.mmoitems.MMOItems.lambda$null$0(MMOItems.java:177) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262]
at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_262]
at net.Indyuce.mmoitems.MMOItems.lambda$onEnable$1(MMOItems.java:177) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-106]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-106]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

WARN
 
10:06:37

[MMOItems]: Task #295 for MMOItems v5.5.3-SNAPSHOT generated an exception

Console
 
10:06:37

java.lang.NullPointerException: null
at net.Indyuce.mmoitems.MMOItems.lambda$null$2(MMOItems.java:184) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_262]
at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_262]
at net.Indyuce.mmoitems.MMOItems.lambda$onEnable$3(MMOItems.java:184) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-106]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-106]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-106]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by Indyuce** [comment]
You have to be more specific, please pastebin your entire server logs and specify how you can reproduce that issue, what plugins might be linked to it, or any other info you may find relevant related to your issue

**Comment by Joshinn-mc** [comment]
Closinng on account of 8 days with no reply.
